### ISSUE TITLE
模型找不到

### ISSUE THREAD

**Issue by RnJnho** [ZubinGou/ResNet-NEU-CLS#2]
博主你好，可以发一下best_resnet18_ImageNet_NEU-64.pth模型么

**Comment by ZubinGou** [comment]
不好意思哈，我没有继续保留模型，有显卡的话可以下载 ImageNet 预训练模型来继续训练下，fine tuning 应该比较快。

**Comment by RnJnho** [comment]
> 不好意思哈，我没有继续保留模型，有显卡的话可以下载 ImageNet 预训练模型来继续训练下，微调应该比较快。

就是说可以使用官方的预训练模型，使用您的代码训练出来么

**Comment by ZubinGou** [comment]
嗯嗯是的
