### ISSUE TITLE
数据集网站打不开了

### ISSUE THREAD

**Issue by G-yjz** [ZubinGou/ResNet-NEU-CLS#3]
你好，我在找一个钢表面缺陷的数据集，公开的网站没有了，那是东北大学的一个数据集，你有保存吗，想要，可以通过微信联系用百度网盘或其他方式发给我吗？我的电话18125864740，求求了谢谢

**Comment by ZubinGou** [comment]
这个或许对你有帮助：https://github.com/abin24/Surface-Inspection-defect-detection-dataset
