### ISSUE TITLE
Ask to share the data set

### ISSUE THREAD

**Issue by lsj0808** [ZubinGou/ResNet-NEU-CLS#4]
Hello, senior,
I am currently studying in Beijing University of Posts and Telecommunications. Could you please share the NEU-CLS-64 data set? The download address of this data set cannot be opened at present. If yes, please send it to our email lsj0805yb@163.com, thank you very much

**Comment by ZubinGou** [comment]
Hi~ Please check [this repository](https://github.com/abin24/Surface-Inspection-defect-detection-dataset) for data.

**Comment by lsj0808** [comment]
Many thanks for this！




















At 2023-07-04 16:07:51, "Zhibin Gou" ***@***.***> wrote:

Hi~ Please check this repository for data.
